version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-$ANDROID_TARGET_VERSION-alpha
    environment:
      TERM: dumb
      JVM_OPTS: -Xmx4g -Xms2g -XX:MaxPermSize=2g
      GIT_COMMIT_DESC: git log --format=oneline -n 1 $CIRCLE_SHA1
      ANDROID_COMPILE_VERSION: 29
      ANDROID_TARGET_VERSION: 29
      ANDROID_MIN_VERSION: 21
      KOTLIN_VERSION: 1.3.11
    java:
      version: oraclejdk8
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results