version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    dependencies:
      pre:
        - sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk/bin/java
        - sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk/bin/javac
        - echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk' >> ~/.circlerc
    java:
      version: 'oraclejdk8'
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results